Chappsolutions/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls import url 
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from searchengine.views import (HomeView, SearchView, 
								HotelListView, HotelDetailView,
								ProfileDetailView, ProfileUpdatelView, ProfileDeleteView,ProfileListView, Gallery)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name = 'search'),
    path('gallery/', Gallery.as_view(), name = 'gallery'),
    path('accounts/', include('allauth.urls')),
    path('account/', include('allauth.urls')),
    path('hotel/', HotelListView.as_view(), name='hotel-list'),     
    path('hotel/<pk>/', HotelDetailView.as_view(), name='hotel-detail'),
    path('profile/', ProfileListView.as_view(), name='profile-list'),   
    path('profile/<pk>/', ProfileDetailView.as_view(), name='profile-detail'),     
    path('profile/<pk>/update/', ProfileUpdatelView.as_view(), name = 'profile-update'),    
    path('profile/<pk>/delete/', ProfileDeleteView.as_view(), name = 'profile-delete'), 

#Api urls
]

urlpatterns += [    
    path('hotelsapi/', include('searchengine.api.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

searchengine/models.py
from django.db import models
from django.urls import reverse
from rest_framework.reverse import reverse as api_reverse
from allauth.account.signals import user_signed_up
from django.contrib.auth import get_user_model
User = get_user_model() 
import datetime
from datetime import date

 

 
class Profile(models.Model):    
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200)
    location =  models.CharField(max_length=200 ,blank=True, null=True)
    photo = models.ImageField(blank=True, null=True)


    def get_absolute_url(self):
        return reverse('profile-detail', kwargs={
            'pk': self.pk
        })



    def __str__(self):
        return self.user.username

def ProfileCallback(sender, request, user, **kwargs):
    userProfile, is_created = Profile.objects.get_or_create(user=user)
    if is_created:
        userProfile.name = user.username
        userProfile.save()

user_signed_up.connect(ProfileCallback)


RoomType = [
        ('Single', 'Singles Rooms'),
        ('Double', 'Doubles Rooms'),    
        ('Triple', 'Triples Rooms'),
        ('Quadruple', 'Quadruples Rooms'),
        ]
price_none = 0
price_single = 20 
price_double = 30   
price_triple = 40 
price_quadruple =50

Prices = [
        (price_none, '-----'),
        (price_single, '€20 / day'),
        (price_double, '€30 / day'),    
        (price_triple, '€40 / day'),
        (price_quadruple, '€50 / day'),
        ]


Room_Status_CHOICE = [   
        ('Avalible', 'Avalible'),
        ('Confirmed', 'Confirmed'),    
        ('Checked_In', 'Checked In'),
        ('Checked_Out', 'Checked Out'),]


class Population(models.Model):
    Roompop =  models.CharField(max_length=20)

    def __str__(self):
        return self.Roompop      

class Hotel_model(models.Model): 

    
    client =  models.ForeignKey(
                            Profile,  
                            on_delete=models.SET_NULL, 
                            blank=True, 
                            null=True )
    
    Room_type = models.CharField(max_length=20,
                            choices=RoomType, 
                            default='Single',
                            help_text='select room type') 

    price = models.IntegerField(choices=Prices, 
                            default=price_none,
                            help_text='add room price')

    Room_status =models.CharField(max_length=20,
                            choices=Room_Status_CHOICE, 
                            default='Avalible',
                            help_text='select Room status',
                            blank=True, null=True)
    Room_pop = models.ManyToManyField(Population, default='1', blank=True)
    Reserved_from = models.DateField(blank=True, null=True)
    Reserved_to = models.DateField(blank=True, null=True)
    Room_number = models.IntegerField()
    Descrition = models.TextField(max_length=200, help_text='a brief description of the hotel room',blank=True, null=True)
    thumbnail = models.ImageField()
    Reservation_ticket =  models.CharField(max_length=20, blank=True, null=True)
    Total_Amount =  models.CharField(max_length=200, blank=True, null=True)


    
    def save(self, *args, **kwargs):
        try:
            try:
                today = datetime.date.today() 

                if today > self.Reserved_to or self.Room_status == 'Avalible':
                    self.client = None
                    self.Room_status = 'Avalible'
                    self.Reserved_from = None 
                    self.Reserved_to = None
                    self.Reservation_ticket = None
                    self.Total_Amount = None

                elif self.Reservation_ticket and self.Reserved_from == today:    
                    self.Room_status = 'Checked_In' 

                elif self.Reservation_ticket and self.Reserved_from != None and self.Reserved_from > today: 
                    self.Room_status = 'Confirmed'
                
                         
            except:
                str_today = f'{datetime.date.today()}' 

                if str_today > self.Reserved_to or self.Room_status == 'Avalible':
                    self.client = None
                    self.Room_status = 'Avalible'
                    self.Reserved_from = None 
                    self.Reserved_to = None
                    self.Reservation_ticket = None
                    self.Total_Amount = None            

                elif self.Reservation_ticket and self.Reserved_from == str_today:    
                    self.Room_status = 'Checked_In' 

                elif self.Reservation_ticket and self.Reserved_from != None and self.Reserved_from > str_today: 
                    self.Room_status = 'Confirmed'
            super(Hotel_model, self).save(*args, **kwargs)
        except:
            super(Hotel_model, self).save(*args, **kwargs)
    


    class Meta:        
        permissions = (("can_validate_ticket", "can validate ticket"),)

    def get_absolute_url(self):
        return reverse('hotel-detail', kwargs={
            'pk': self.pk
        })
    def get_api_url(self, request=None):
        return api_reverse("hotel-api", kwargs={'pk': self.pk}, request=request)

    def __str__(self):
        return self.Room_type[0]

templates/hotel/hotel_detail.html
{% extends 'base/content_base.html' %}
{% load staticfiles %}
{% block script%}
{% endblock %} 
{% load crispy_forms_tags %}
{% block content  %}

{% if hotel.Room_status == 'Avalible' %}
<h1></h1>
<h1 class="">
       <p class="header-line text-center h1">BOOKING PAGE</p>
</h1> 
<p class="text-center">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. enean commodo.<br />
Lorem ipsum dolor sit amet,consectetuer <br />
adipiscing elit. Aenean commodo</p>
<div class="container well">
       <div class="row">
              <div class="col-md-6 col-md-offset-1">              
                {% if hotel.thumbnail %}
                <img src="{{ hotel.thumbnail.url }}" class="img-rounded img-fluid post-list-img" id="detail-image"/>
                {% else %}
                <img src="{% static 'images/badge.png' %}" class="img-rounded img-fluid post-list-img" id="detail-image"/>
                {% endif %}
              </div>
              <style type="text/css">
                .pay-param i{

                }
              </style>
              <div class="h3 col-md-5">
                                    
                        <table>
                          <p class="">
                          <tr class=""><b class="">Room Number:</b></tr>&emsp;&nbsp;
                         
                          <tr class="">{{hotel.Room_number}}</tr><br /></p>

                          <p>
                          <tr class=""><b class="">Room Type:</b></tr>
                          &emsp;&emsp;&emsp;
                          <tr class=""> {{hotel.Room_type}}</tr><br /></p>

                          <p>
                          <tr class=""><b class="text-left">From:</b></tr>
                          &emsp;&emsp;&emsp;&emsp;&emsp;&ensp;&nbsp;
                          <tr class=""> {{from}}</tr><br /></p>

                          <p>
                          <tr class=""><b class="text-left">To:</b></tr>
                          &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;
                          <tr class="">{{to}}</tr><br /></p>

                          <p>
                          <tr class=""><b class="text-left">Duration:</b></tr>
                          &emsp;&emsp;&emsp;&nbsp;&ensp;
                          <tr class="">{{duration}}Day{{duration|pluralize}}</tr><br /></p>

                          <p>
                          <tr class=""><b class="text-left">Status:</b></tr>
                          &emsp;&emsp;&emsp;&emsp;&ensp;&nbsp;&nbsp;&nbsp;
                          <tr class="">{{hotel.Room_status}}</tr><br /></p>

                          <p>
                          <tr class=""><b class="text-left">Amount:</b></tr>
                          &emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;
                          <tr class=""><u>€{% widthratio hotel.price 1 duration %}</u></tr></p>
                        </table>                                
                    </div>        
         </div>
    </div>
 <hr />     
 <style type="text/css">
   #card-element{
   
    border:  #1c2b4b 1px solid;
    color: black;
   }
 </style>
<center class="container">
    <div class="row">
          <div class="col-md-6 col-md-offset-3">           
                    <script src="https://js.stripe.com/v3/"></script>
                     <form action="." method="post" id="payment-form" enctype="multipart/form-data">
                            {% csrf_token %}
                       
                         <div class="form-row">
                           <label for="card-element">
                             <p class="h3"></strong>Make payment</strong></p>
                             <p class="h5 text-center">Credit or debit card</p>
                           </label>
                           <div id="card-element">
                             <!-- A Stripe Element will be inserted here. -->
                           </div>
                           <!-- Used to display form errors. -->
                           <div id="card-errors" role="alert"></div>
                         </div>
                         <br />                         
                         <input type="hidden" name="Reserved_from" id="id_Reserved_from" value="{{from}}" readonly/>
                         <input type="hidden" name="Reserved_to" id="id_Reserved_to" value="{{to}}" readonly/>
                         <input type="hidden" name="Total_Amount" maxlength="200" id="id_Total_Amount" value="{% widthratio hotel.price 1 duration %}" readonly/>                       
                          <input type="hidden" name="hotel_id" id="hotel_id" value="{{hotel.id}}" readonly/>
                         <center><input type="submit" class="btn btn-info text-center" value ="Pay" /></center>
                     </form>
            </div>
      </div>
</center>

<hr>
<script type="text/javascript">
  
  // Create a Stripe client.
var stripe = Stripe('{{publishKey}}');
// Create an instance of Elements.
var elements = stripe.elements();
// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('payment-form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('payment-form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}
</script>




{% else %}
<ul> 
    <center class="top10" style="position:relative; padding-bottom: 7vw; bottom: 0; padding-top: 70px;">
    <p class="well h3">
      THIS ROOM IS CURRENLY NOT AVALIBLE <br /> SEARCH AND BOOK A ROOM <br >
        <a class="btn btn-info btn-lg" href="/search/">HERE</a>
  </p>
    
    
</center>
</ul> 

{% endif %}
{% endblock%}

templates/hotel/hotel_list.html
{% extends 'base/content_base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content  %}

{% for rooms in hotel_list|slice:"1" %}
<div id="" class="container">   
        <div class="row text-center">
            <div class="col-lg-8 col-lg-offset-2">
                <h1 data-scroll-reveal="enter from the bottom after 0.2s"  class="header-line">AVALIBLES ROOMS FOR YOUR BOOKING </h1>
                <h5 data-scroll-reveal="enter from the bottom after 0.3s" >
                    The following Rooms are avalible for booking <h4>From <b>{{from}}</b> To <b>{{to}}</b></h4>
                 Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                   Aenean commodo.
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                   Aenean commodo.
                    </h5>
            </div>
        </div>
   
</div>
 {%empty%} 
 <div id="features-sec" class="container set-pad">  
        <div class="row text-center">
            <div class="col-lg-8 col-lg-offset-2">
                <h1 data-scroll-reveal="enter from the bottom after 0.2s"  class="header-line">IT SEEM WE ARE ALL BOOKED UP FOR THIS CATEGORY! </h1>
                <p data-scroll-reveal="enter from the bottom after 0.3s" >
                  <h4>From <b>{{from}}</b> To <b>{{to}}</b></h4>
                 Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                   Aenean commodo.
                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                   Aenean commodo.
                    </p>
                      <center>
                        <a href="/search/" class="label label-info"><i class="btn btn-info btn-xl">PLSEASE CHECK OTHER CATEGORIES</i> </a>
                    </center>
                    <br />
            </div>
        </div> 
</div> 
{% endfor %}
 <div class="container" style="background: radial-gradient(circle, #3f51b500 0%, #3F51B5 100%);">
            <div class="row">           
             
{% for rooms in hotel_list %} 
{% if rooms.Room_status == 'Avalible' and not room.Reservation_ticket %}      
   
              <div class="col-lg-4 well" style="padding-top: 30px; padding-bottom: 30px;">
                <a href="{{ rooms.get_absolute_url }}">          
                    {% if rooms.thumbnail %}
                    <img src="{{ rooms.thumbnail.url }}" class="img-rounded img-fluid img-responsive" id="list-image"/>
                    {% else %}
                    <img src="{% static 'images/badge.png' %}" class="img-rounded img-fluid img-responsive" id="list-image"  />
                    {% endif %}
                </a>               
                   <center class="text-left ">     
               <hr />
                    <b class="h3">{{rooms.Room_type|upper}}: {{rooms.Room_number}}</b>                   
                    <p class="" style="">{{rooms.Descrition}}</p>
                    <i class="h5"><b>Price for {{total_days}} Day{{total_days|pluralize}}:</b>
                         <h4>€{% widthratio rooms.price 1 total_days %}</h4> </i>       
                    <b> @ €{{rooms.price}}</b>/day 
                    <div class="text-info">
                        <button  class="btn-primary btn-xs">
                             <a href="{{rooms.get_absolute_url}}"  style="color:aliceblue">Book Now!</a>
                        </button>
                    </div>                    
                    </center>  
             </div>   
 {% endif %}                
{% endfor %}

<!--Pagniation-->
           
        </div>
    </div> 
{% endblock%}